const info = {
  code: "SUCCESS",
  data: {
    canEdit: false,
    canView: true,
    createTime: "2024-06-06 15:31:35",
    creatorId: "1",
    creatorName: "系统管理员",
    currentNodeId: "5266",
    currentNodeName: "1、申请人申请",
    forwardButtonName: "",
    lastOperateTime: "2024-06-06 15:34:33",
    lastOperatorName: "",
    messageType: "0",
    mustInputRemark: false,
    needAffirmance: false,
    rejectButtonName: "",
    remark: "",
    requestId: "422364",
    requestLevel: "0",
    requestName:
      "物品采购申请流程(2023-11-24 09:08:31导入测试)-系统管理员-2024-06-06",
    status: "2.5、设备科确认",
    subbackButtonName: "",
    submitButtonName: "",
    subnobackButtonName: "",
    workflowBaseInfo: {
      workflowId: "731",
      workflowName: "物品采购申请流程(2023-11-24 09:08:31导入测试)",
      workflowTypeId: "32",
      workflowTypeName: "流程测试区",
    },
    workflowDetailTableInfos: [
      {
        tableDBName: "formtable_main_353_dt1",
        tableFieldName: [
          "品名",
          "规格",
          "单位",
          "申请数量",
          "产品质量要求",
          "厂家单价",
          "建议厂家",
          "交货日期",
          "备注",
          "京东单价",
          "物料编号",
          "厂家编号",
        ],
        tableTitle: "",
        workflowRequestTableRecords: [
          {
            recordOrder: 63,
            workflowRequestTableFields: [
              {
                browserurl: "",
                edit: true,
                fieldDBType: "varchar(500)",
                fieldFormName: "field16832_0",
                fieldHtmlType: "1",
                fieldId: "16832",
                fieldName: "mx001",
                fieldOrder: 0,
                fieldShowName: "品名",
                fieldShowValue: "活扳手",
                fieldType: "1",
                fieldValue: "活扳手",
                filedHtmlShow:
                  '<table style="width:100%;"><tr><td style="width:99%;white-space:normal;" align="left"><input type="text" name="field16832_0" id="mx001" value="活扳手" onChange="checkLength(\'field16832_0\',500, \'品名\', \'文本长度不能超过\', \'1个中文字符等于3个长度\');"/></td><td><span id="mx001_ismandspan" class="ismand">!</span><input type="hidden" id="ismandfield" name="ismandfield" value="mx001"/></td></tr></table>',
                mand: true,
                selectnames: [],
                selectvalues: [],
                view: true,
              },
              {
                browserurl: "",
                edit: true,
                fieldDBType: "varchar(500)",
                fieldFormName: "field16833_0",
                fieldHtmlType: "1",
                fieldId: "16833",
                fieldName: "mx002",
                fieldOrder: 0,
                fieldShowName: "规格",
                fieldShowValue: "6寸",
                fieldType: "1",
                fieldValue: "6寸",
                filedHtmlShow:
                  '<table style="width:100%;"><tr><td style="width:99%;white-space:normal;" align="left"><input type="text" name="field16833_0" id="mx002" value="6寸" onChange="checkLength(\'field16833_0\',500, \'规格\', \'文本长度不能超过\', \'1个中文字符等于3个长度\');"/></td><td><span id="mx002_ismandspan" class="ismand">!</span><input type="hidden" id="ismandfield" name="ismandfield" value="mx002"/></td></tr></table>',
                mand: true,
                selectnames: [],
                selectvalues: [],
                view: true,
              },
              {
                browserurl: "",
                edit: true,
                fieldDBType: "varchar(500)",
                fieldFormName: "field16834_0",
                fieldHtmlType: "1",
                fieldId: "16834",
                fieldName: "mx003",
                fieldOrder: 0,
                fieldShowName: "单位",
                fieldShowValue: "把",
                fieldType: "1",
                fieldValue: "把",
                filedHtmlShow:
                  '<table style="width:100%;"><tr><td style="width:99%;white-space:normal;" align="left"><input type="text" name="field16834_0" id="mx003" value="把" onChange="checkLength(\'field16834_0\',500, \'单位\', \'文本长度不能超过\', \'1个中文字符等于3个长度\');"/></td><td><span id="mx003_ismandspan" class="ismand">!</span><input type="hidden" id="ismandfield" name="ismandfield" value="mx003"/></td></tr></table>',
                mand: true,
                selectnames: [],
                selectvalues: [],
                view: true,
              },
              {
                browserurl: "",
                edit: true,
                fieldDBType: "decimal(38,2)",
                fieldFormName: "field16835_0",
                fieldHtmlType: "1",
                fieldId: "16835",
                fieldName: "mx004",
                fieldOrder: 0,
                fieldShowName: "申请数量",
                fieldShowValue: "12.00",
                fieldType: "3",
                fieldValue: "12.00",
                filedHtmlShow:
                  '<table style="width:100%;"><tr><td style="width:99%;white-space:normal;" align="left"><input type="text" onkeypress="ItemNum_KeyPress(\'field16835_0\')" onblur="checknumber1(this);" name="field16835_0" id="mx004" value="12.00" /></td><td><span id="mx004_ismandspan" class="ismand">!</span><input type="hidden" id="ismandfield" name="ismandfield" value="mx004"/></td></tr></table>',
                mand: true,
                selectnames: [],
                selectvalues: [],
                view: true,
              },
              {
                browserurl: "",
                edit: true,
                fieldDBType: "varchar(500)",
                fieldFormName: "field16836_0",
                fieldHtmlType: "1",
                fieldId: "16836",
                fieldName: "mx005",
                fieldOrder: 0,
                fieldShowName: "产品质量要求",
                fieldShowValue: "无",
                fieldType: "1",
                fieldValue: "无",
                filedHtmlShow:
                  '<table style="width:100%;"><tr><td style="width:99%;white-space:normal;" align="left"><input type="text" name="field16836_0" id="mx005" value="无" onChange="checkLength(\'field16836_0\',500, \'产品质量要求\', \'文本长度不能超过\', \'1个中文字符等于3个长度\');"/></td></tr></table>',
                mand: false,
                selectnames: [],
                selectvalues: [],
                view: true,
              },
              {
                browserurl: "",
                edit: true,
                fieldDBType: "decimal(38,2)",
                fieldFormName: "field16837_0",
                fieldHtmlType: "1",
                fieldId: "16837",
                fieldName: "mx006",
                fieldOrder: 0,
                fieldShowName: "厂家单价",
                fieldShowValue: "10.00",
                fieldType: "3",
                fieldValue: "10.00",
                filedHtmlShow:
                  '<table style="width:100%;"><tr><td style="width:99%;white-space:normal;" align="left"><input type="text" onkeypress="ItemNum_KeyPress(\'field16837_0\')" onblur="checknumber1(this);" name="field16837_0" id="mx006" value="10.00" /></td></tr></table>',
                mand: false,
                selectnames: [],
                selectvalues: [],
                view: true,
              },
              {
                browserurl: "",
                edit: true,
                fieldDBType: "varchar(500)",
                fieldFormName: "field16838_0",
                fieldHtmlType: "1",
                fieldId: "16838",
                fieldName: "mx007",
                fieldOrder: 0,
                fieldShowName: "建议厂家",
                fieldShowValue: "河北青阳羊绒制品有限公司",
                fieldType: "1",
                fieldValue: "河北青阳羊绒制品有限公司",
                filedHtmlShow:
                  '<table style="width:100%;"><tr><td style="width:99%;white-space:normal;" align="left"><input type="text" name="field16838_0" id="mx007" value="河北青阳羊绒制品有限公司" onChange="checkLength(\'field16838_0\',500, \'建议厂家\', \'文本长度不能超过\', \'1个中文字符等于3个长度\');"/></td></tr></table>',
                mand: false,
                selectnames: [],
                selectvalues: [],
                view: true,
              },
              {
                browserurl: "",
                edit: true,
                fieldDBType: "char(10)",
                fieldFormName: "field16839_0",
                fieldHtmlType: "3",
                fieldId: "16839",
                fieldName: "mx008",
                fieldOrder: 0,
                fieldShowName: "交货日期",
                fieldShowValue: "2024-06-28",
                fieldType: "2",
                fieldValue: "2024-06-28",
                filedHtmlShow:
                  '<table style="width:100%;"><tr><td style="width:99%;white-space:normal;" align="left"><input type="text" name="field16839_0" id="mx008" value="2024-06-28" /></td></tr></table>',
                mand: false,
                selectnames: [],
                selectvalues: [],
                view: true,
              },
              {
                browserurl: "",
                edit: true,
                fieldDBType: "varchar(500)",
                fieldFormName: "field16840_0",
                fieldHtmlType: "1",
                fieldId: "16840",
                fieldName: "mx009",
                fieldOrder: 0,
                fieldShowName: "备注",
                fieldShowValue: "2024年6月6日15:30:59测试1",
                fieldType: "1",
                fieldValue: "2024年6月6日15:30:59测试1",
                filedHtmlShow:
                  '<table style="width:100%;"><tr><td style="width:99%;white-space:normal;" align="left"><input type="text" name="field16840_0" id="mx009" value="2024年6月6日15:30:59测试1" onChange="checkLength(\'field16840_0\',500, \'备注\', \'文本长度不能超过\', \'1个中文字符等于3个长度\');"/></td></tr></table>',
                mand: false,
                selectnames: [],
                selectvalues: [],
                view: true,
              },
              {
                browserurl: "",
                edit: true,
                fieldDBType: "decimal(38,2)",
                fieldFormName: "field16841_0",
                fieldHtmlType: "1",
                fieldId: "16841",
                fieldName: "mx010",
                fieldOrder: 0,
                fieldShowName: "京东单价",
                fieldShowValue: "",
                fieldType: "3",
                fieldValue: "",
                filedHtmlShow:
                  '<table style="width:100%;"><tr><td style="width:99%;white-space:normal;" align="left"><input type="text" onkeypress="ItemNum_KeyPress(\'field16841_0\')" onblur="checknumber1(this);" name="field16841_0" id="mx010" value="" /></td></tr></table>',
                mand: false,
                selectnames: [],
                selectvalues: [],
                view: true,
              },
              {
                browserurl: "",
                edit: true,
                fieldDBType: "browser.HS_vwmmMaterialHardware",
                fieldFormName: "field16861_0",
                fieldHtmlType: "3",
                fieldId: "16861",
                fieldName: "wlbh",
                fieldOrder: 0,
                fieldShowName: "物料编号",
                fieldShowValue:
                  "<a title='活扳手'>05.20.01.015</a>&nbsp<span style='color:#ACA899'>[该字段仅支持显示]</span>",
                fieldType: "161",
                fieldValue: "05.20.01.015",
                filedHtmlShow:
                  "<div style=\"width:100%;\"><a title='活扳手'>05.20.01.015</a>&nbsp<span style='color:#ACA899'>[该字段仅支持显示]</span></div>",
                mand: false,
                selectnames: [],
                selectvalues: [],
                view: true,
              },
              {
                browserurl: "",
                edit: true,
                fieldDBType: "browser.HS_vwmmHWStoreCheckItem",
                fieldFormName: "field16862_0",
                fieldHtmlType: "3",
                fieldId: "16862",
                fieldName: "cjbh",
                fieldOrder: 0,
                fieldShowName: "厂家编号",
                fieldShowValue:
                  "<a title='河北青阳羊绒制品有限公司'>1.208</a>&nbsp<span style='color:#ACA899'>[该字段仅支持显示]</span>",
                fieldType: "161",
                fieldValue: "1.208",
                filedHtmlShow:
                  "<div style=\"width:100%;\"><a title='河北青阳羊绒制品有限公司'>1.208</a>&nbsp<span style='color:#ACA899'>[该字段仅支持显示]</span></div>",
                mand: false,
                selectnames: [],
                selectvalues: [],
                view: true,
              },
            ],
          },
          {
            recordOrder: 64,
            workflowRequestTableFields: [
              {
                browserurl: "",
                edit: true,
                fieldDBType: "varchar(500)",
                fieldFormName: "field16832_0",
                fieldHtmlType: "1",
                fieldId: "16832",
                fieldName: "mx001",
                fieldOrder: 0,
                fieldShowName: "品名",
                fieldShowValue: "齿形带",
                fieldType: "1",
                fieldValue: "齿形带",
                filedHtmlShow:
                  '<table style="width:100%;"><tr><td style="width:99%;white-space:normal;" align="left"><input type="text" name="field16832_0" id="mx001" value="齿形带" onChange="checkLength(\'field16832_0\',500, \'品名\', \'文本长度不能超过\', \'1个中文字符等于3个长度\');"/></td><td><span id="mx001_ismandspan" class="ismand">!</span><input type="hidden" id="ismandfield" name="ismandfield" value="mx001"/></td></tr></table>',
                mand: true,
                selectnames: [],
                selectvalues: [],
                view: true,
              },
              {
                browserurl: "",
                edit: true,
                fieldDBType: "varchar(500)",
                fieldFormName: "field16833_0",
                fieldHtmlType: "1",
                fieldId: "16833",
                fieldName: "mx002",
                fieldOrder: 0,
                fieldShowName: "规格",
                fieldShowValue: "22*CX-2540",
                fieldType: "1",
                fieldValue: "22*CX-2540",
                filedHtmlShow:
                  '<table style="width:100%;"><tr><td style="width:99%;white-space:normal;" align="left"><input type="text" name="field16833_0" id="mx002" value="22*CX-2540" onChange="checkLength(\'field16833_0\',500, \'规格\', \'文本长度不能超过\', \'1个中文字符等于3个长度\');"/></td><td><span id="mx002_ismandspan" class="ismand">!</span><input type="hidden" id="ismandfield" name="ismandfield" value="mx002"/></td></tr></table>',
                mand: true,
                selectnames: [],
                selectvalues: [],
                view: true,
              },
              {
                browserurl: "",
                edit: true,
                fieldDBType: "varchar(500)",
                fieldFormName: "field16834_0",
                fieldHtmlType: "1",
                fieldId: "16834",
                fieldName: "mx003",
                fieldOrder: 0,
                fieldShowName: "单位",
                fieldShowValue: "条",
                fieldType: "1",
                fieldValue: "条",
                filedHtmlShow:
                  '<table style="width:100%;"><tr><td style="width:99%;white-space:normal;" align="left"><input type="text" name="field16834_0" id="mx003" value="条" onChange="checkLength(\'field16834_0\',500, \'单位\', \'文本长度不能超过\', \'1个中文字符等于3个长度\');"/></td><td><span id="mx003_ismandspan" class="ismand">!</span><input type="hidden" id="ismandfield" name="ismandfield" value="mx003"/></td></tr></table>',
                mand: true,
                selectnames: [],
                selectvalues: [],
                view: true,
              },
              {
                browserurl: "",
                edit: true,
                fieldDBType: "decimal(38,2)",
                fieldFormName: "field16835_0",
                fieldHtmlType: "1",
                fieldId: "16835",
                fieldName: "mx004",
                fieldOrder: 0,
                fieldShowName: "申请数量",
                fieldShowValue: "4.00",
                fieldType: "3",
                fieldValue: "4.00",
                filedHtmlShow:
                  '<table style="width:100%;"><tr><td style="width:99%;white-space:normal;" align="left"><input type="text" onkeypress="ItemNum_KeyPress(\'field16835_0\')" onblur="checknumber1(this);" name="field16835_0" id="mx004" value="4.00" /></td><td><span id="mx004_ismandspan" class="ismand">!</span><input type="hidden" id="ismandfield" name="ismandfield" value="mx004"/></td></tr></table>',
                mand: true,
                selectnames: [],
                selectvalues: [],
                view: true,
              },
              {
                browserurl: "",
                edit: true,
                fieldDBType: "varchar(500)",
                fieldFormName: "field16836_0",
                fieldHtmlType: "1",
                fieldId: "16836",
                fieldName: "mx005",
                fieldOrder: 0,
                fieldShowName: "产品质量要求",
                fieldShowValue: "6A",
                fieldType: "1",
                fieldValue: "6A",
                filedHtmlShow:
                  '<table style="width:100%;"><tr><td style="width:99%;white-space:normal;" align="left"><input type="text" name="field16836_0" id="mx005" value="6A" onChange="checkLength(\'field16836_0\',500, \'产品质量要求\', \'文本长度不能超过\', \'1个中文字符等于3个长度\');"/></td></tr></table>',
                mand: false,
                selectnames: [],
                selectvalues: [],
                view: true,
              },
              {
                browserurl: "",
                edit: true,
                fieldDBType: "decimal(38,2)",
                fieldFormName: "field16837_0",
                fieldHtmlType: "1",
                fieldId: "16837",
                fieldName: "mx006",
                fieldOrder: 0,
                fieldShowName: "厂家单价",
                fieldShowValue: "15.00",
                fieldType: "3",
                fieldValue: "15.00",
                filedHtmlShow:
                  '<table style="width:100%;"><tr><td style="width:99%;white-space:normal;" align="left"><input type="text" onkeypress="ItemNum_KeyPress(\'field16837_0\')" onblur="checknumber1(this);" name="field16837_0" id="mx006" value="15.00" /></td></tr></table>',
                mand: false,
                selectnames: [],
                selectvalues: [],
                view: true,
              },
              {
                browserurl: "",
                edit: true,
                fieldDBType: "varchar(500)",
                fieldFormName: "field16838_0",
                fieldHtmlType: "1",
                fieldId: "16838",
                fieldName: "mx007",
                fieldOrder: 0,
                fieldShowName: "建议厂家",
                fieldShowValue: "杭州正百电子商行",
                fieldType: "1",
                fieldValue: "杭州正百电子商行",
                filedHtmlShow:
                  '<table style="width:100%;"><tr><td style="width:99%;white-space:normal;" align="left"><input type="text" name="field16838_0" id="mx007" value="杭州正百电子商行" onChange="checkLength(\'field16838_0\',500, \'建议厂家\', \'文本长度不能超过\', \'1个中文字符等于3个长度\');"/></td></tr></table>',
                mand: false,
                selectnames: [],
                selectvalues: [],
                view: true,
              },
              {
                browserurl: "",
                edit: true,
                fieldDBType: "char(10)",
                fieldFormName: "field16839_0",
                fieldHtmlType: "3",
                fieldId: "16839",
                fieldName: "mx008",
                fieldOrder: 0,
                fieldShowName: "交货日期",
                fieldShowValue: "2024-06-27",
                fieldType: "2",
                fieldValue: "2024-06-27",
                filedHtmlShow:
                  '<table style="width:100%;"><tr><td style="width:99%;white-space:normal;" align="left"><input type="text" name="field16839_0" id="mx008" value="2024-06-27" /></td></tr></table>',
                mand: false,
                selectnames: [],
                selectvalues: [],
                view: true,
              },
              {
                browserurl: "",
                edit: true,
                fieldDBType: "varchar(500)",
                fieldFormName: "field16840_0",
                fieldHtmlType: "1",
                fieldId: "16840",
                fieldName: "mx009",
                fieldOrder: 0,
                fieldShowName: "备注",
                fieldShowValue: "2024年6月6日15:31:26测试2",
                fieldType: "1",
                fieldValue: "2024年6月6日15:31:26测试2",
                filedHtmlShow:
                  '<table style="width:100%;"><tr><td style="width:99%;white-space:normal;" align="left"><input type="text" name="field16840_0" id="mx009" value="2024年6月6日15:31:26测试2" onChange="checkLength(\'field16840_0\',500, \'备注\', \'文本长度不能超过\', \'1个中文字符等于3个长度\');"/></td></tr></table>',
                mand: false,
                selectnames: [],
                selectvalues: [],
                view: true,
              },
              {
                browserurl: "",
                edit: true,
                fieldDBType: "decimal(38,2)",
                fieldFormName: "field16841_0",
                fieldHtmlType: "1",
                fieldId: "16841",
                fieldName: "mx010",
                fieldOrder: 0,
                fieldShowName: "京东单价",
                fieldShowValue: "",
                fieldType: "3",
                fieldValue: "",
                filedHtmlShow:
                  '<table style="width:100%;"><tr><td style="width:99%;white-space:normal;" align="left"><input type="text" onkeypress="ItemNum_KeyPress(\'field16841_0\')" onblur="checknumber1(this);" name="field16841_0" id="mx010" value="" /></td></tr></table>',
                mand: false,
                selectnames: [],
                selectvalues: [],
                view: true,
              },
              {
                browserurl: "",
                edit: true,
                fieldDBType: "browser.HS_vwmmMaterialHardware",
                fieldFormName: "field16861_0",
                fieldHtmlType: "3",
                fieldId: "16861",
                fieldName: "wlbh",
                fieldOrder: 0,
                fieldShowName: "物料编号",
                fieldShowValue:
                  "<a title='齿形带'>05.30.01.412</a>&nbsp<span style='color:#ACA899'>[该字段仅支持显示]</span>",
                fieldType: "161",
                fieldValue: "05.30.01.412",
                filedHtmlShow:
                  "<div style=\"width:100%;\"><a title='齿形带'>05.30.01.412</a>&nbsp<span style='color:#ACA899'>[该字段仅支持显示]</span></div>",
                mand: false,
                selectnames: [],
                selectvalues: [],
                view: true,
              },
              {
                browserurl: "",
                edit: true,
                fieldDBType: "browser.HS_vwmmHWStoreCheckItem",
                fieldFormName: "field16862_0",
                fieldHtmlType: "3",
                fieldId: "16862",
                fieldName: "cjbh",
                fieldOrder: 0,
                fieldShowName: "厂家编号",
                fieldShowValue:
                  "<a title='杭州正百电子商行'>2.318</a>&nbsp<span style='color:#ACA899'>[该字段仅支持显示]</span>",
                fieldType: "161",
                fieldValue: "2.318",
                filedHtmlShow:
                  "<div style=\"width:100%;\"><a title='杭州正百电子商行'>2.318</a>&nbsp<span style='color:#ACA899'>[该字段仅支持显示]</span></div>",
                mand: false,
                selectnames: [],
                selectvalues: [],
                view: true,
              },
            ],
          },
        ],
      },
    ],
    workflowHtmlShow: ["", null],
    workflowHtmlTemplete: ["", null],
    workflowMainTableInfo: {
      requestRecords: [
        {
          recordOrder: 0,
          workflowRequestTableFields: [
            {
              edit: false,
              fieldDBType: "",
              fieldFormName: "requestname",
              fieldHtmlType: "1",
              fieldId: "-1",
              fieldName: "requestname",
              fieldOrder: -1,
              fieldShowName: "标题",
              fieldShowValue:
                "物品采购申请流程(2023-11-24 09:08:31导入测试)-系统管理员-2024-06-06",
              fieldType: "",
              fieldValue:
                "物品采购申请流程(2023-11-24 09:08:31导入测试)-系统管理员-2024-06-06",
              filedHtmlShow:
                "物品采购申请流程(2023-11-24 09:08:31导入测试)-系统管理员-2024-06-06",
              mand: true,
              view: true,
            },
            {
              edit: false,
              fieldDBType: "",
              fieldFormName: "requestlevel",
              fieldHtmlType: "5",
              fieldId: "-2",
              fieldName: "requestlevel",
              fieldOrder: -2,
              fieldShowName: "",
              fieldShowValue: "正常",
              fieldType: "",
              fieldValue: "0",
              filedHtmlShow: "正常",
              mand: false,
              selectnames: ["正常", "重要", "紧急"],
              selectvalues: ["0", "1", "2"],
              view: true,
            },
            {
              edit: false,
              fieldDBType: "",
              fieldFormName: "messageType",
              fieldHtmlType: "5",
              fieldId: "-3",
              fieldName: "messageType",
              fieldOrder: -3,
              fieldShowName: "短信提醒",
              fieldShowValue: "不短信提醒",
              fieldType: "",
              fieldValue: "0",
              filedHtmlShow: "",
              mand: false,
              selectnames: ["不短信提醒", "离线短信提醒", "在线短信提醒"],
              selectvalues: ["0", "1", "2"],
              view: false,
            },
            {
              browserurl: "",
              edit: true,
              fieldDBType: "int",
              fieldFormName: "field16858",
              fieldHtmlType: "5",
              fieldId: "16858",
              fieldName: "cglx",
              fieldOrder: 1,
              fieldShowName: "采购类型",
              fieldShowValue: "备品备件采购",
              fieldType: "1",
              fieldValue: "2",
              filedHtmlShow:
                '<table style="width:100%;"><tr><td style="width:99%;white-space:normal;" align="left"><select name="field16858" id="cglx"><option value="" ></option><option value="0" >办公用品采购（非信息类）</option><option value="8" >办公用品采购（信息类）</option><option value="1" >常规配件采购</option><option value="2" selected>备品备件采购</option><option value="3" >固定资产采购</option><option value="4" >礼品采购</option><option value="5" >服务采购</option><option value="6" >常规染化料助剂采购</option><option value="7" >纸管及纸箱</option></select></td><td><span id="cglx_ismandspan" class="ismand">!</span><input type="hidden" id="ismandfield" name="ismandfield" value="cglx"/></td></tr></table>',
              mand: true,
              selectnames: [
                "办公用品采购（非信息类）",
                "办公用品采购（信息类）",
                "常规配件采购",
                "备品备件采购",
                "固定资产采购",
                "礼品采购",
                "服务采购",
                "常规染化料助剂采购",
                "纸管及纸箱",
              ],
              selectvalues: ["0", "8", "1", "2", "3", "4", "5", "6", "7"],
              view: true,
            },
            {
              browserurl: "",
              edit: true,
              fieldDBType: "int",
              fieldFormName: "field16859",
              fieldHtmlType: "5",
              fieldId: "16859",
              fieldName: "lplx",
              fieldOrder: 2,
              fieldShowName: "礼品类型",
              fieldShowValue: "",
              fieldType: "1",
              fieldValue: "",
              filedHtmlShow:
                '<table style="width:100%;"><tr><td style="width:99%;white-space:normal;" align="left"><select name="field16859" id="lplx"><option value="" selected></option><option value="0" >常规礼品</option><option value="1" >其他礼品</option></select></td><td><span id="lplx_ismandspan" class="ismand">!</span><input type="hidden" id="ismandfield" name="ismandfield" value="lplx"/></td></tr></table>',
              mand: true,
              selectnames: ["常规礼品", "其他礼品"],
              selectvalues: ["0", "1"],
              view: true,
            },
            {
              browserurl: "",
              edit: false,
              fieldDBType: "int",
              fieldFormName: "field16860",
              fieldHtmlType: "5",
              fieldId: "16860",
              fieldName: "sqgs",
              fieldOrder: 4,
              fieldShowName: "申请公司",
              fieldShowValue: "",
              fieldType: "1",
              fieldValue: "",
              filedHtmlShow: "",
              mand: false,
              selectnames: ["中鼎纺织", "中鼎科技"],
              selectvalues: ["0", "1"],
              view: false,
            },
            {
              browserurl: "",
              edit: false,
              fieldDBType: "int",
              fieldFormName: "field16842",
              fieldHtmlType: "3",
              fieldId: "16842",
              fieldName: "sqr",
              fieldOrder: 7,
              fieldShowName: "申请人",
              fieldShowValue: "系统管理员 ",
              fieldType: "1",
              fieldValue: "1",
              filedHtmlShow: "系统管理员 ",
              mand: false,
              selectnames: [],
              selectvalues: [],
              view: true,
            },
            {
              browserurl: "",
              edit: false,
              fieldDBType: "int",
              fieldFormName: "field16843",
              fieldHtmlType: "3",
              fieldId: "16843",
              fieldName: "sqbm",
              fieldOrder: 8,
              fieldShowName: "申请部门",
              fieldShowValue: "信息部 ",
              fieldType: "4",
              fieldValue: "61",
              filedHtmlShow: "信息部 ",
              mand: false,
              selectnames: [],
              selectvalues: [],
              view: true,
            },
            {
              browserurl: "",
              edit: false,
              fieldDBType: "char(10)",
              fieldFormName: "field16844",
              fieldHtmlType: "3",
              fieldId: "16844",
              fieldName: "sqrq",
              fieldOrder: 11,
              fieldShowName: "申请日期",
              fieldShowValue: "2024-06-06",
              fieldType: "2",
              fieldValue: "2024-06-06",
              filedHtmlShow: "2024-06-06",
              mand: false,
              selectnames: [],
              selectvalues: [],
              view: true,
            },
            {
              browserurl: "",
              edit: false,
              fieldDBType: "varchar(500)",
              fieldFormName: "field16845",
              fieldHtmlType: "1",
              fieldId: "16845",
              fieldName: "lcbh",
              fieldOrder: 12,
              fieldShowName: "流程编号",
              fieldShowValue: "WJCGCS-20240606-004",
              fieldType: "1",
              fieldValue: "WJCGCS-20240606-004",
              filedHtmlShow: "WJCGCS-20240606-004",
              mand: false,
              selectnames: [],
              selectvalues: [],
              view: true,
            },
            {
              browserurl: "",
              edit: true,
              fieldDBType: "text",
              fieldFormName: "field16846",
              fieldHtmlType: "3",
              fieldId: "16846",
              fieldName: "xglc",
              fieldOrder: 15,
              fieldShowName: "相关流程",
              fieldShowValue: "",
              fieldType: "152",
              fieldValue: "",
              filedHtmlShow:
                '<table style="width:100%;"><tr><td style="width:10%;" onclick="javascript:showDialog(\'/browser/dialog.do\',\'&returnIdField=xglc&returnShowField=xglc_span&method=listWorkflowRequest&isMuti=1\')"><a href="#" data-rel="dialog" data-transition="pop"><div style="background-image:url(\'/images/search_icon_wev8.png\');height:30px;width:30px;"></div></a><input type="hidden" name="field16846" id="xglc" value=""/></td><td id="xglc_span" style="width:90%;white-space:normal;" align="left"></td></tr></table>',
              mand: false,
              selectnames: [],
              selectvalues: [],
              view: true,
            },
            {
              browserurl: "",
              edit: true,
              fieldDBType: "text",
              fieldFormName: "field16847",
              fieldHtmlType: "3",
              fieldId: "16847",
              fieldName: "xgwd",
              fieldOrder: 16,
              fieldShowName: "相关文档",
              fieldShowValue: "",
              fieldType: "37",
              fieldValue: "",
              filedHtmlShow:
                '<table style="width:100%;"><tr><td style="width:10%;" onclick="javascript:showDialog(\'/browser/dialog.do\',\'&returnIdField=xgwd&returnShowField=xgwd_span&method=listDocument&isMuti=1\')"><a href="#" data-rel="dialog" data-transition="pop"><div style="background-image:url(\'/images/search_icon_wev8.png\');height:30px;width:30px;"></div></a><input type="hidden" name="field16847" id="xgwd" value=""/></td><td id="xgwd_span" style="width:90%;white-space:normal;" align="left" jsfn=\'toDocument\'></td></tr></table>',
              mand: false,
              selectnames: [],
              selectvalues: [],
              view: true,
            },
            {
              browserurl: "",
              edit: true,
              fieldDBType: "text",
              fieldFormName: "field16848",
              fieldHtmlType: "6",
              fieldId: "16848",
              fieldName: "xgfj",
              fieldOrder: 19,
              fieldShowName: "相关附件",
              fieldShowValue:
                "<span style='color:#ACA899'>[该字段暂不支持]</span>",
              fieldType: "1",
              fieldValue: "",
              filedHtmlShow:
                "<span style='color:#ACA899'>[该字段暂不支持]</span>",
              mand: false,
              selectnames: [],
              selectvalues: [],
              view: true,
            },
            {
              browserurl: "",
              edit: false,
              fieldDBType: "int",
              fieldFormName: "field16849",
              fieldHtmlType: "3",
              fieldId: "16849",
              fieldName: "gs",
              fieldOrder: 21,
              fieldShowName: "公司",
              fieldShowValue: "中鼎纺织 ",
              fieldType: "164",
              fieldValue: "1",
              filedHtmlShow: "中鼎纺织 ",
              mand: false,
              selectnames: [],
              selectvalues: [],
              view: true,
            },
            {
              browserurl: "",
              edit: false,
              fieldDBType: "int",
              fieldFormName: "field16850",
              fieldHtmlType: "5",
              fieldId: "16850",
              fieldName: "cght001",
              fieldOrder: 22,
              fieldShowName: "采购类型",
              fieldShowValue: "",
              fieldType: "1",
              fieldValue: "",
              filedHtmlShow: "",
              mand: false,
              selectnames: [
                "原料",
                "五金",
                "办公用品",
                "备品备件",
                "固定资产",
                "礼品物品",
              ],
              selectvalues: ["0", "1", "2", "3", "4", "5"],
              view: false,
            },
            {
              browserurl: "",
              edit: false,
              fieldDBType: "int",
              fieldFormName: "field16851",
              fieldHtmlType: "5",
              fieldId: "16851",
              fieldName: "cght002",
              fieldOrder: 24,
              fieldShowName: "所属",
              fieldShowValue: "",
              fieldType: "1",
              fieldValue: "",
              filedHtmlShow: "",
              mand: false,
              selectnames: ["车间", "行政"],
              selectvalues: ["0", "1"],
              view: false,
            },
            {
              browserurl: "",
              edit: true,
              fieldDBType: "text",
              fieldFormName: "field16852",
              fieldHtmlType: "2",
              fieldId: "16852",
              fieldName: "cght003",
              fieldOrder: 25,
              fieldShowName: "说明",
              fieldShowValue: "",
              fieldType: "1",
              fieldValue: "",
              filedHtmlShow:
                '<table style="width:100%;"><tr><td style="width:99%;white-space:normal;" align="left"><textarea cols="40" rows="8" name="field16852" id="cght003" ></textarea></td></tr></table>',
              mand: false,
              selectnames: [],
              selectvalues: [],
              view: true,
            },
            {
              browserurl: "",
              edit: false,
              fieldDBType: "decimal(38,2)",
              fieldFormName: "field16853",
              fieldHtmlType: "1",
              fieldId: "16853",
              fieldName: "cght004",
              fieldOrder: 26,
              fieldShowName: "金额",
              fieldShowValue: "15.00",
              fieldType: "3",
              fieldValue: "15.00",
              filedHtmlShow: "15.00",
              mand: false,
              selectnames: [],
              selectvalues: [],
              view: true,
            },
            {
              browserurl: "",
              edit: false,
              fieldDBType: "decimal(38,2)",
              fieldFormName: "field16854",
              fieldHtmlType: "1",
              fieldId: "16854",
              fieldName: "cght005",
              fieldOrder: 27,
              fieldShowName: "大写",
              fieldShowValue: "",
              fieldType: "3",
              fieldValue: "",
              filedHtmlShow: "",
              mand: false,
              selectnames: [],
              selectvalues: [],
              view: false,
            },
            {
              browserurl: "",
              edit: false,
              fieldDBType: "text",
              fieldFormName: "field16855",
              fieldHtmlType: "7",
              fieldId: "16855",
              fieldName: "zb001",
              fieldOrder: 28,
              fieldShowName: "办公用品分类",
              fieldShowValue:
                "第一类：办公家具类，包括办公桌、办公椅、会议椅、档案柜、沙发、茶几等非电器类较大型的办公陈设。 <br>第二类：信息设备类，包括电脑、传真机、打印机、碎纸机、扫描仪、投影仪、移动硬盘、电话机、显示屏等。 <br>第三类：劳保用品类，工作服、口罩、工作鞋等。 <br>第四类：低值易耗品，办公耗材、办公文具，包括硒鼓、墨盒、碳粉、复印纸、计算器、订书机、剪刀等；胶水、单/双面胶带、图钉、回形针、笔记本、便签、笔芯、圆珠笔、文件夹、文件袋、档案袋、档案盒印泥、白板笔、记号笔、荧光笔、修正液、订书针、尺、电池、长尾夹、复印纸、复写纸、纸类印刷品等。 <br>第五类：生活及待客用品，包括餐巾纸、擦手纸、卷纸、洗手液、洁厕灵、防臭球、纸杯、茶叶、矿泉水、拖把、扫帚、畚箕、垃圾桶等。 <br>第六类：绿化类，绿植、绿化工具等相关物品。",
              fieldType: "2",
              fieldValue: "",
              filedHtmlShow:
                "第一类：办公家具类，包括办公桌、办公椅、会议椅、档案柜、沙发、茶几等非电器类较大型的办公陈设。 <br>第二类：信息设备类，包括电脑、传真机、打印机、碎纸机、扫描仪、投影仪、移动硬盘、电话机、显示屏等。 <br>第三类：劳保用品类，工作服、口罩、工作鞋等。 <br>第四类：低值易耗品，办公耗材、办公文具，包括硒鼓、墨盒、碳粉、复印纸、计算器、订书机、剪刀等；胶水、单/双面胶带、图钉、回形针、笔记本、便签、笔芯、圆珠笔、文件夹、文件袋、档案袋、档案盒印泥、白板笔、记号笔、荧光笔、修正液、订书针、尺、电池、长尾夹、复印纸、复写纸、纸类印刷品等。 <br>第五类：生活及待客用品，包括餐巾纸、擦手纸、卷纸、洗手液、洁厕灵、防臭球、纸杯、茶叶、矿泉水、拖把、扫帚、畚箕、垃圾桶等。 <br>第六类：绿化类，绿植、绿化工具等相关物品。",
              mand: false,
              selectnames: [],
              selectvalues: [],
              view: true,
            },
            {
              browserurl: "",
              edit: false,
              fieldDBType: "text",
              fieldFormName: "field16856",
              fieldHtmlType: "3",
              fieldId: "16856",
              fieldName: "zb002",
              fieldOrder: 29,
              fieldShowName: "相关领导",
              fieldShowValue: "",
              fieldType: "17",
              fieldValue: "",
              filedHtmlShow: "",
              mand: false,
              selectnames: [],
              selectvalues: [],
              view: true,
            },
            {
              browserurl: "",
              edit: false,
              fieldDBType: "int",
              fieldFormName: "field16857",
              fieldHtmlType: "5",
              fieldId: "16857",
              fieldName: "zb003",
              fieldOrder: 30,
              fieldShowName: "执行部门",
              fieldShowValue: "五金仓",
              fieldType: "1",
              fieldValue: "0",
              filedHtmlShow: "五金仓",
              mand: false,
              selectnames: ["五金仓", "采购部", "信息部", "行政人事部"],
              selectvalues: ["0", "1", "2", "3"],
              view: true,
            },
          ],
        },
      ],
      tableDBName: "formtable_main_353",
    },
    workflowRequestLogs: [
      {
        annexDocHtmls: "",
        id: "1365050",
        nodeId: "5266",
        nodeName: "1、申请人申请",
        operateDate: "2024-06-06",
        operateTime: "15:31:47",
        operateType: "提交",
        operatorId: "1",
        operatorName: "系统管理员",
        receivedPersons: "傅志武",
        remark: "",
        signDocHtmls: "",
        signWorkFlowHtmls: "",
      },
      {
        annexDocHtmls: "",
        id: "1365053",
        nodeId: "5268",
        nodeName: "2、部门负责人审核",
        operateDate: "2024-06-06",
        operateTime: "15:34:33",
        operateType: "批准",
        operatorDept: "信息部",
        operatorId: "2059",
        operatorName: "傅志武",
        receivedPersons: "傅志武",
        remark: "",
        signDocHtmls: "",
        signWorkFlowHtmls: "",
      },
    ],
  },
  errMsg: {},
};

function script(params) {
  const parentObject = [];
  params.data.workflowMainTableInfo.requestRecords.forEach((obj) => {
    obj.workflowRequestTableFields.forEach((field) => {
      if (field.fieldName === "cglx") {
        parentObject.push(field);
      }
    });
  });
  var res = {};
  res.data = parentObject;
  return res;
}

console.log("script(data) :>> ", script(info));
