/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AppNode: typeof import('./../src/components/AutoDnd/components/nodes/appNode.vue')['default']
    AutoDnd: typeof import('./../src/components/AutoDnd/AutoDnd.vue')['default']
    AutoForm: typeof import('./../src/components/AutoForm/AutoForm.vue')['default']
    CardBox: typeof import('./../src/components/CardBox/CardBox.vue')['default']
    ChatBox: typeof import('./../src/components/StreamPrint/ChatBox.vue')['default']
    ChatMsgItem: typeof import('./../src/components/StreamPrint/ChatMsgItem.vue')['default']
    EdgeNode: typeof import('./../src/components/AutoDnd/components/edges/edgeNode.vue')['default']
    EndNode: typeof import('./../src/components/AutoDnd/components/nodes/endNode.vue')['default']
    FloatButton: typeof import('./../src/components/FloatButton/FloatButton.vue')['default']
    FlowLine: typeof import('./../src/components/AutoDnd/components/edges/flowLine.vue')['default']
    InfiniteScroll: typeof import('./../src/components/InfiniteScroll/index.vue')['default']
    LazyLoadImg: typeof import('./../src/components/LazyLoadImg/index.vue')['default']
    MarkedView: typeof import('./../src/components/MarkedView/MarkedView.vue')['default']
    NodeBox: typeof import('./../src/components/AutoDnd/components/nodeBox.vue')['default']
    NodeDnd: typeof import('./../src/components/AutoDnd/components/nodeDnd.vue')['default']
    Panel: typeof import('./../src/components/Panel/Panel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scroll: typeof import('./../src/components/ScrollMore/Scroll.vue')['default']
    ScrollMore: typeof import('./../src/components/ScrollMore/index.vue')['default']
    StartNode: typeof import('./../src/components/AutoDnd/components/nodes/startNode.vue')['default']
    StreamPrint: typeof import('./../src/components/StreamPrint/index.vue')['default']
    SvgIcon: typeof import('./../src/components/SvgIcon/SvgIcon.vue')['default']
    TagTextInput: typeof import('./../src/components/TagTextMixInput/TagTextInput.vue')['default']
    TagTextMixInput: typeof import('./../src/components/TagTextMixInput/index.vue')['default']
    WarefallFow: typeof import('./../src/components/WarefallFlow/WarefallFow.vue')['default']
    Xtable: typeof import('./../src/components/Xtable/index.vue')['default']
    XTable: typeof import('./../src/components/Xtable/XTable.vue')['default']
  }
}
