/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    CardBox: typeof import('./../components/CardBox/CardBox.vue')['default']
    FloatButton: typeof import('./../components/FloatButton/FloatButton.vue')['default']
    MarkedView: typeof import('./../components/MarkedView/MarkedView.vue')['default']
    Panel: typeof import('./../components/Panel/Panel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/SvgIcon/SvgIcon.vue')['default']
  }
}
