/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    AutoForm: typeof import('./../components/AutoForm/AutoForm.vue')['default']
    CardBox: typeof import('./../components/CardBox/CardBox.vue')['default']
    ChatBox: typeof import('./../components/StreamPrint/ChatBox.vue')['default']
    ChatMsgItem: typeof import('./../components/StreamPrint/ChatMsgItem.vue')['default']
    FloatButton: typeof import('./../components/FloatButton/FloatButton.vue')['default']
    InfiniteScroll: typeof import('./../components/InfiniteScroll/index.vue')['default']
    LazyLoadImg: typeof import('./../components/LazyLoadImg/index.vue')['default']
    MarkedView: typeof import('./../components/MarkedView/MarkedView.vue')['default']
    Panel: typeof import('./../components/Panel/Panel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollMore: typeof import('./../components/ScrollMore/index.vue')['default']
    StreamPrint: typeof import('./../components/StreamPrint/index.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/SvgIcon.vue')['default']
    TagTextMixInput: typeof import('./../components/TagTextMixInput/index.vue')['default']
    WarefallFow: typeof import('./../components/WarefallFlow/WarefallFow.vue')['default']
    Xtable: typeof import('./../components/Xtable/index.vue')['default']
    XTable: typeof import('./../components/Xtable/XTable.vue')['default']
  }
}
