// function script(params) {
//   var res = {};
//   var filterKey = ["mx005", "mx007", "mx009", "wlbh", "cjbh"];
//   params.forEach((obj) => {
//     if (filterKey.includes(obj.fieldName)) {
//       res[obj.fieldName] = obj.fieldName;
//     }
//   });
//   return res;
// }

function script(params) {
  var filterKey = ["mx005", "mx007", "mx009", "wlbh", "cjbh"];
  return params.reduce((pre, next) => {
    if (filterKey.includes(next.fieldName)) {
      pre[next.fieldName] = next.fieldName;
    }
    return pre;
  }, {});
}

const data = [
  {
    edit: false,
    fieldDBType: "",
    fieldFormName: "requestname",
    fieldHtmlType: "1",
    fieldId: "-1",
    fieldName: "mx005",
    fieldOrder: -1,
    fieldShowName: "标题",
    fieldShowValue:
      "物品采购申请流程(2023-11-24 09:08:31导入测试)-系统管理员-2024-06-06",
    fieldType: "",
    fieldValue:
      "物品采购申请流程(2023-11-24 09:08:31导入测试)-系统管理员-2024-06-06",
    filedHtmlShow:
      "物品采购申请流程(2023-11-24 09:08:31导入测试)-系统管理员-2024-06-06",
    mand: true,
    view: true,
  },
  {
    edit: false,
    fieldDBType: "",
    fieldFormName: "requestlevel",
    fieldHtmlType: "5",
    fieldId: "-2",
    fieldName: "requestlevel",
    fieldOrder: -2,
    fieldShowName: "",
    fieldShowValue: "正常",
    fieldType: "",
    fieldValue: "0",
    filedHtmlShow: "正常",
    mand: false,
    selectnames: ["正常", "重要", "紧急"],
    selectvalues: ["0", "1", "2"],
    view: true,
  },
  {
    edit: false,
    fieldDBType: "",
    fieldFormName: "messageType",
    fieldHtmlType: "5",
    fieldId: "-3",
    fieldName: "messageType",
    fieldOrder: -3,
    fieldShowName: "短信提醒",
    fieldShowValue: "不短信提醒",
    fieldType: "",
    fieldValue: "0",
    filedHtmlShow: "",
    mand: false,
    selectnames: ["不短信提醒", "离线短信提醒", "在线短信提醒"],
    selectvalues: ["0", "1", "2"],
    view: false,
  },
  {
    browserurl: "",
    edit: true,
    fieldDBType: "int",
    fieldFormName: "field16858",
    fieldHtmlType: "5",
    fieldId: "16858",
    fieldName: "cglx",
    fieldOrder: 1,
    fieldShowName: "采购类型",
    fieldShowValue: "备品备件采购",
    fieldType: "1",
    fieldValue: "2",
    filedHtmlShow:
      '<table style="width:100%;"><tr><td style="width:99%;white-space:normal;" align="left"><select name="field16858" id="cglx"><option value="" ></option><option value="0" >办公用品采购（非信息类）</option><option value="8" >办公用品采购（信息类）</option><option value="1" >常规配件采购</option><option value="2" selected>备品备件采购</option><option value="3" >固定资产采购</option><option value="4" >礼品采购</option><option value="5" >服务采购</option><option value="6" >常规染化料助剂采购</option><option value="7" >纸管及纸箱</option></select></td><td><span id="cglx_ismandspan" class="ismand">!</span><input type="hidden" id="ismandfield" name="ismandfield" value="cglx"/></td></tr></table>',
    mand: true,
    selectnames: [
      "办公用品采购（非信息类）",
      "办公用品采购（信息类）",
      "常规配件采购",
      "备品备件采购",
      "固定资产采购",
      "礼品采购",
      "服务采购",
      "常规染化料助剂采购",
      "纸管及纸箱",
    ],
    selectvalues: ["0", "8", "1", "2", "3", "4", "5", "6", "7"],
    view: true,
  },
  {
    browserurl: "",
    edit: true,
    fieldDBType: "int",
    fieldFormName: "field16859",
    fieldHtmlType: "5",
    fieldId: "16859",
    fieldName: "lplx",
    fieldOrder: 2,
    fieldShowName: "礼品类型",
    fieldShowValue: "",
    fieldType: "1",
    fieldValue: "",
    filedHtmlShow:
      '<table style="width:100%;"><tr><td style="width:99%;white-space:normal;" align="left"><select name="field16859" id="lplx"><option value="" selected></option><option value="0" >常规礼品</option><option value="1" >其他礼品</option></select></td><td><span id="lplx_ismandspan" class="ismand">!</span><input type="hidden" id="ismandfield" name="ismandfield" value="lplx"/></td></tr></table>',
    mand: true,
    selectnames: ["常规礼品", "其他礼品"],
    selectvalues: ["0", "1"],
    view: true,
  },
  {
    browserurl: "",
    edit: false,
    fieldDBType: "int",
    fieldFormName: "field16860",
    fieldHtmlType: "5",
    fieldId: "16860",
    fieldName: "sqgs",
    fieldOrder: 4,
    fieldShowName: "申请公司",
    fieldShowValue: "",
    fieldType: "1",
    fieldValue: "",
    filedHtmlShow: "",
    mand: false,
    selectnames: ["中鼎纺织", "中鼎科技"],
    selectvalues: ["0", "1"],
    view: false,
  },
  {
    browserurl: "",
    edit: false,
    fieldDBType: "int",
    fieldFormName: "field16842",
    fieldHtmlType: "3",
    fieldId: "16842",
    fieldName: "sqr",
    fieldOrder: 7,
    fieldShowName: "申请人",
    fieldShowValue: "系统管理员 ",
    fieldType: "1",
    fieldValue: "1",
    filedHtmlShow: "系统管理员 ",
    mand: false,
    selectnames: [],
    selectvalues: [],
    view: true,
  },
  {
    browserurl: "",
    edit: false,
    fieldDBType: "int",
    fieldFormName: "field16843",
    fieldHtmlType: "3",
    fieldId: "16843",
    fieldName: "sqbm",
    fieldOrder: 8,
    fieldShowName: "申请部门",
    fieldShowValue: "信息部 ",
    fieldType: "4",
    fieldValue: "61",
    filedHtmlShow: "信息部 ",
    mand: false,
    selectnames: [],
    selectvalues: [],
    view: true,
  },
  {
    browserurl: "",
    edit: false,
    fieldDBType: "char(10)",
    fieldFormName: "field16844",
    fieldHtmlType: "3",
    fieldId: "16844",
    fieldName: "sqrq",
    fieldOrder: 11,
    fieldShowName: "申请日期",
    fieldShowValue: "2024-06-06",
    fieldType: "2",
    fieldValue: "2024-06-06",
    filedHtmlShow: "2024-06-06",
    mand: false,
    selectnames: [],
    selectvalues: [],
    view: true,
  },
  {
    browserurl: "",
    edit: false,
    fieldDBType: "varchar(500)",
    fieldFormName: "field16845",
    fieldHtmlType: "1",
    fieldId: "16845",
    fieldName: "lcbh",
    fieldOrder: 12,
    fieldShowName: "流程编号",
    fieldShowValue: "WJCGCS-20240606-004",
    fieldType: "1",
    fieldValue: "WJCGCS-20240606-004",
    filedHtmlShow: "WJCGCS-20240606-004",
    mand: false,
    selectnames: [],
    selectvalues: [],
    view: true,
  },
  {
    browserurl: "",
    edit: true,
    fieldDBType: "text",
    fieldFormName: "field16846",
    fieldHtmlType: "3",
    fieldId: "16846",
    fieldName: "xglc",
    fieldOrder: 15,
    fieldShowName: "相关流程",
    fieldShowValue: "",
    fieldType: "152",
    fieldValue: "",
    filedHtmlShow:
      '<table style="width:100%;"><tr><td style="width:10%;" onclick="javascript:showDialog(\'/browser/dialog.do\',\'&returnIdField=xglc&returnShowField=xglc_span&method=listWorkflowRequest&isMuti=1\')"><div style="background-image:url(\'/images/search_icon_wev8.png\');height:30px;width:30px;"></div><input type="hidden" name="field16846" id="xglc" value=""/></td><td id="xglc_span" style="width:90%;white-space:normal;" align="left"></td></tr></table>',
    mand: false,
    selectnames: [],
    selectvalues: [],
    view: true,
  },
  {
    browserurl: "",
    edit: true,
    fieldDBType: "text",
    fieldFormName: "field16847",
    fieldHtmlType: "3",
    fieldId: "16847",
    fieldName: "xgwd",
    fieldOrder: 16,
    fieldShowName: "相关文档",
    fieldShowValue: "",
    fieldType: "37",
    fieldValue: "",
    filedHtmlShow:
      '<table style="width:100%;"><tr><td style="width:10%;" onclick="javascript:showDialog(\'/browser/dialog.do\',\'&returnIdField=xgwd&returnShowField=xgwd_span&method=listDocument&isMuti=1\')"><a href="#" data-rel="dialog" data-transition="pop"><div style="background-image:url(\'/images/search_icon_wev8.png\');height:30px;width:30px;"></div></a ><input type="hidden" name="field16847" id="xgwd" value=""/></td><td id="xgwd_span" style="width:90%;white-space:normal;" align="left" jsfn=\'toDocument\'></td></tr></table>',
    mand: false,
    selectnames: [],
    selectvalues: [],
    view: true,
  },
  {
    browserurl: "",
    edit: true,
    fieldDBType: "text",
    fieldFormName: "field16848",
    fieldHtmlType: "6",
    fieldId: "16848",
    fieldName: "xgfj",
    fieldOrder: 19,
    fieldShowName: "相关附件",
    fieldShowValue: "<span style='color:#ACA899'>[该字段暂不支持]</span>",
    fieldType: "1",
    fieldValue: "",
    filedHtmlShow: "<span style='color:#ACA899'>[该字段暂不支持]</span>",
    mand: false,
    selectnames: [],
    selectvalues: [],
    view: true,
  },
  {
    browserurl: "",
    edit: false,
    fieldDBType: "int",
    fieldFormName: "field16849",
    fieldHtmlType: "3",
    fieldId: "16849",
    fieldName: "gs",
    fieldOrder: 21,
    fieldShowName: "公司",
    fieldShowValue: "中鼎纺织 ",
    fieldType: "164",
    fieldValue: "1",
    filedHtmlShow: "中鼎纺织 ",
    mand: false,
    selectnames: [],
    selectvalues: [],
    view: true,
  },
  {
    browserurl: "",
    edit: false,
    fieldDBType: "int",
    fieldFormName: "field16850",
    fieldHtmlType: "5",
    fieldId: "16850",
    fieldName: "cght001",
    fieldOrder: 22,
    fieldShowName: "采购类型",
    fieldShowValue: "",
    fieldType: "1",
    fieldValue: "",
    filedHtmlShow: "",
    mand: false,
    selectnames: [
      "原料",
      "五金",
      "办公用品",
      "备品备件",
      "固定资产",
      "礼品物品",
    ],
    selectvalues: ["0", "1", "2", "3", "4", "5"],
    view: false,
  },
  {
    browserurl: "",
    edit: false,
    fieldDBType: "int",
    fieldFormName: "field16851",
    fieldHtmlType: "5",
    fieldId: "16851",
    fieldName: "cght002",
    fieldOrder: 24,
    fieldShowName: "所属",
    fieldShowValue: "",
    fieldType: "1",
    fieldValue: "",
    filedHtmlShow: "",
    mand: false,
    selectnames: ["车间", "行政"],
    selectvalues: ["0", "1"],
    view: false,
  },
  {
    browserurl: "",
    edit: true,
    fieldDBType: "text",
    fieldFormName: "field16852",
    fieldHtmlType: "2",
    fieldId: "16852",
    fieldName: "cght003",
    fieldOrder: 25,
    fieldShowName: "说明",
    fieldShowValue: "",
    fieldType: "1",
    fieldValue: "",
    filedHtmlShow:
      '<table style="width:100%;"><tr><td style="width:99%;white-space:normal;" align="left"><textarea cols="40" rows="8" name="field16852" id="cght003" ></textarea></td></tr></table>',
    mand: false,
    selectnames: [],
    selectvalues: [],
    view: true,
  },
  {
    browserurl: "",
    edit: false,
    fieldDBType: "decimal(38,2)",
    fieldFormName: "field16853",
    fieldHtmlType: "1",
    fieldId: "16853",
    fieldName: "cght004",
    fieldOrder: 26,
    fieldShowName: "金额",
    fieldShowValue: "15.00",
    fieldType: "3",
    fieldValue: "15.00",
    filedHtmlShow: "15.00",
    mand: false,
    selectnames: [],
    selectvalues: [],
    view: true,
  },
  {
    browserurl: "",
    edit: false,
    fieldDBType: "decimal(38,2)",
    fieldFormName: "field16854",
    fieldHtmlType: "1",
    fieldId: "16854",
    fieldName: "cght005",
    fieldOrder: 27,
    fieldShowName: "大写",
    fieldShowValue: "",
    fieldType: "3",
    fieldValue: "",
    filedHtmlShow: "",
    mand: false,
    selectnames: [],
    selectvalues: [],
    view: false,
  },
  {
    browserurl: "",
    edit: false,
    fieldDBType: "text",
    fieldFormName: "field16855",
    fieldHtmlType: "7",
    fieldId: "16855",
    fieldName: "zb001",
    fieldOrder: 28,
    fieldShowName: "办公用品分类",
    fieldShowValue:
      "第一类：办公家具类，包括办公桌、办公椅、会议椅、档案柜、沙发、茶几等非电器类较大型的办公陈设。 <br>第二类：信息设备类，包括电脑、传真机、打印机、碎纸机、扫描仪、投影仪、移动硬盘、电话机、显示屏等。 <br>第三类：劳保用品类，工作服、口罩、工作鞋等。 <br>第四类：低值易耗品，办公耗材、办公文具，包括硒鼓、墨盒、碳粉、复印纸、计算器、订书机、剪刀等；胶水、单/双面胶带、图钉、回形针、笔记本、便签、笔芯、圆珠笔、文件夹、文件袋、档案袋、档案盒印泥、白板笔、记号笔、荧光笔、修正液、订书针、尺、电池、长尾夹、复印纸、复写纸、纸类印刷品等。 <br>第五类：生活及待客用品，包括餐巾纸、擦手纸、卷纸、洗手液、洁厕灵、防臭球、纸杯、茶叶、矿泉水、拖把、扫帚、畚箕、垃圾桶等。 <br>第六类：绿化类，绿植、绿化工具等相关物品。",
    fieldType: "2",
    fieldValue: "",
    filedHtmlShow:
      "第一类：办公家具类，包括办公桌、办公椅、会议椅、档案柜、沙发、茶几等非电器类较大型的办公陈设。 <br>第二类：信息设备类，包括电脑、传真机、打印机、碎纸机、扫描仪、投影仪、移动硬盘、电话机、显示屏等。 <br>第三类：劳保用品类，工作服、口罩、工作鞋等。 <br>第四类：低值易耗品，办公耗材、办公文具，包括硒鼓、墨盒、碳粉、复印纸、计算器、订书机、剪刀等；胶水、单/双面胶带、图钉、回形针、笔记本、便签、笔芯、圆珠笔、文件夹、文件袋、档案袋、档案盒印泥、白板笔、记号笔、荧光笔、修正液、订书针、尺、电池、长尾夹、复印纸、复写纸、纸类印刷品等。 <br>第五类：生活及待客用品，包括餐巾纸、擦手纸、卷纸、洗手液、洁厕灵、防臭球、纸杯、茶叶、矿泉水、拖把、扫帚、畚箕、垃圾桶等。 <br>第六类：绿化类，绿植、绿化工具等相关物品。",
    mand: false,
    selectnames: [],
    selectvalues: [],
    view: true,
  },
  {
    browserurl: "",
    edit: false,
    fieldDBType: "text",
    fieldFormName: "field16856",
    fieldHtmlType: "3",
    fieldId: "16856",
    fieldName: "zb002",
    fieldOrder: 29,
    fieldShowName: "相关领导",
    fieldShowValue: "",
    fieldType: "17",
    fieldValue: "",
    filedHtmlShow: "",
    mand: false,
    selectnames: [],
    selectvalues: [],
    view: true,
  },
  {
    browserurl: "",
    edit: false,
    fieldDBType: "int",
    fieldFormName: "field16857",
    fieldHtmlType: "5",
    fieldId: "16857",
    fieldName: "zb003",
    fieldOrder: 30,
    fieldShowName: "执行部门",
    fieldShowValue: "五金仓",
    fieldType: "1",
    fieldValue: "0",
    filedHtmlShow: "五金仓",
    mand: false,
    selectnames: ["五金仓", "采购部", "信息部", "行政人事部"],
    selectvalues: ["0", "1", "2", "3"],
    view: true,
  },
];

console.log("script(data) :>> ", script(data));
